spring.application.name=MoveEasy
spring.datasource.url=jdbc:postgresql://localhost:5432/MoveEasy
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=sign_docs_secret_key_123
jwt.expiration= 3600000
file.upload-dir=secure-storage/documents

spring.security.oauth2.client.registration.google.client-id=346846065143-qbjpdvie4a40uviunbr0sk6tq8gfqo96.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile